language: python

cache:
    pip: true
    directories:
    - .tox

matrix:
    include:
      - python: 2.7
          env:
            - TOX_ENV=py27
      - python: 3.6
          env:
            - TOX_ENV=py36
            - TOX_ENV=flake8

install:
  - pip install --upgrade pip
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success: test $TOX_ENV = "py36" && coveralls
