language: python

python: 3.5

cache:
    pip: true
    directories:
    - .tox

env:
  matrix:
    - TOX_ENV=py35
    - TOX_ENV=flake8
    - TOX_ENV=spelling

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success: test $TOX_ENV = "py35" && coveralls
