language: python

cache:
    pip: true
    directories:
    - .tox

matrix:
    include:
      - python: 3.5
          env:
            - TOX_ENV=py35
            - TOX_ENV=flake8

install:
  - pip install --upgrade pip
  - pip install tox coveralls

script:
  - tox -e $TOX_ENV

after_success: test $TOX_ENV = "py35" && coveralls
