# Time constants
DAYS_IN_YEAR = 365
HOURS_IN_DAY = 24
MIN_IN_HOUR = 60
SEC_IN_MIN = 60
SEC_IN_HOUR = SEC_IN_MIN * MIN_IN_HOUR
SEC_IN_DAY = SEC_IN_HOUR * HOURS_IN_DAY
SEC_IN_YEAR = SEC_IN_DAY * DAYS_IN_YEAR

gamma_const = 1.781072  # exp(Euler's constant)
